config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  
  root 'static_pages#home'
  
  
  get '/home' =>      'static_pages#home'
  get '/egresados' => 'static_pages#egresados'
  get '/acercade' =>  'static_pages#about'
  
  get '/contacts',     to: 'contacts#new'
  resources "contacts", only: [:new, :create]
  
  
  resources :notices
  
  resources :users, only: [:index, :show, :edit,:update,:destroy]
  
  
  get 'principal/index'
  get 'evento' => 'evento#listar'
  get 'evento/nuevo' => 'evento#nuevo'
  post 'evento/nuevo' => 'evento#nuevo'
  post 'evento/crear' => 'evento#crear'
  get 'evento/crear' => 'evento#crear'
  get 'evento/eliminar' => 'evento#eliminar'
  post 'evento/eliminar' => 'evento#eliminar'
  get 'evento/mostrar'
  get 'evento/modificar' => 'evento#modificar'
  post 'evento/modificar' => 'evento#modificar'
  

end

app/models/notice.rb
class Notice < ActiveRecord::Base
    
    belongs_to :user
    
    validates :title, presence: true, length: { minimum: 3 }
    validates :body, presence: true, length: { minimum: 30 }
    
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController

    before_filter :authorize_admin, only: [:new,:create]
    #los usuarios puede ver solo si estan logueados
    #before_filter :authenticate_user! #, only: [:show, :index]
    
    def index
        #@notices = Notice.all
        @notices = Notice.order('created_at DESC').page(params[:page]).per(15)
    end
    
    def show
        @notice = Notice.find(params[:id])
    end
    
    def new
        @notice = Notice.new
    end
    
    def create
        @user = current_user
        @notice = Notice.new(allowed_params)
    
        if @notice.save
            flash[:success] = "Created new notice"
            redirect_to @notice
        else
            render 'new'
        end
    end
    
    private
        def allowed_params
            params.require(:notice).permit(:title, :body)
        end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
            <br>
            <% if current_user.role ==1 %>
            <%= link_to 'Crear Noticia', new_notice_path, class:'btn btn-default btn-md' %>
            <% end %>
            <%= paginate(@notices) %>
            
            
              <h2>Noticias</h2>
              <p> Noticias del Tecn&oacute;logo</p>
                  <% @notices.each do |p| %>    
                    
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title"><%= link_to p.title, notice_path(p.id) %></h3>
                  </div>
                  <div class="panel-body">
                    <%= p.body %>
                  </div>
                </div>
              <% end %>
              
            
        <%= paginate(@notices) %>
        </div>
    </div>
</div>

<style>
    footer {
        bottom:0;
    }
</style>

app/views/notices/new.html.erb
<div class="container" style="margin-top:20px; margin-bottom:20px;">
    <div class="row">
        <div class="col-lg-10 col-lg-offset-2">
            <%= form_for @notice do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
                <div class="form-group">
                    <%= f.label :Titulo, class: 'control-label' %>
                    <%= f.text_field :title, class: 'form-control' %>
                </div>
        
                <div class="form-group">
                    <%= f.label :Contenido, class: 'control-label' %>
                    <%= f.text_area :body, class: 'form-control', rows: 10 %>
                </div>
        
                <%= f.submit 'Save', class: 'btn btn-primary' %>
            <% end %>

        </div>
    </div>    
</div>

app/views/notices/show.html.erb
   
<div class="container">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3">   
           
           <div class="page-header">
              <h1><%= @notice.title %></h1>
            </div>
           
            <p><%= @notice.body %></p>
            <p><%= (@notice.fecha).strftime('%m/%d/%Y') %></p>
        </div>
    </div>
</div>

<style>
    footer {
        bottom:0;
    }
    
    .users.row {
    -moz-column-width: 15em;
    -webkit-column-width: 15em;
    -moz-column-gap: 0;
    -webkit-column-gap: 0;
}

@media (min-width: 992px) {
    .users.row {
        -moz-column-width: 13.5em;
        -webkit-column-width: 13.5em;
    }
}
</style>